import {useEffect, useRef, useState} from 'react';
import {Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions} from 'react-native';
import {Button, Loading, ScreenHeader} from '../components/ui';
import {colors, radius, spacing} from '../theme';
import type {ShepherdAttendanceApi} from './shepherdAttendanceApi';
import {validateAttendanceInput} from './shepherdAttendanceDomain';
import type {AdminAttendancePage, AttendanceInput, ShepherdGroup} from './shepherdAttendanceTypes';

type Member = {userId?: number; id?: number; name: string};
export function AdminShepherdAttendanceScreen({api, campusId, getAccessToken, members, onBack}: {api: ShepherdAttendanceApi; campusId: number; getAccessToken: () => Promise<string>; members: Member[]; onBack: () => void}) {
  const {width} = useWindowDimensions();
  const [serviceDate, setServiceDate] = useState(currentSunday());
  const [page, setPage] = useState(0);
  const [data, setData] = useState<AdminAttendancePage | null>(null);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'ALL' | 'SUBMITTED' | 'MISSING'>('ALL');
  const [editing, setEditing] = useState<ShepherdGroup | null>(null);
  const [input, setInput] = useState<AttendanceInput>({smallGroupMeetingCount: '', holyWaveCount: '', otherWorshipCount: '', note: ''});
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [newGroupName, setNewGroupName] = useState('');
  const [newAssignees, setNewAssignees] = useState<number[]>([]);
  const [assigneeGroup, setAssigneeGroup] = useState<ShepherdGroup | null>(null);
  const [assigneeSelection, setAssigneeSelection] = useState<number[]>([]);
  const sequence = useRef(0);
  const load = async () => { const current = ++sequence.current; setLoading(true); setError(null); try { const next = await api.getAdminPage(await getAccessToken(), campusId, serviceDate, page, 50); if (current === sequence.current) setData(next); } catch { if (current === sequence.current) setError('목홀타 현황을 불러오지 못했습니다.'); } finally { if (current === sequence.current) setLoading(false); } };
  useEffect(() => { void load(); return () => { sequence.current += 1; }; }, [campusId, page, serviceDate]);
  const moveWeek = (days: number) => { const next = new Date(`${serviceDate}T12:00:00+09:00`); next.setDate(next.getDate() + days); setPage(0); setServiceDate(formatDate(next)); };
  const rows = (data?.content ?? []).filter((group) => filter === 'ALL' || (filter === 'SUBMITTED' ? group.report?.status === 'SUBMITTED' : group.report?.status !== 'SUBMITTED'));
  const startEdit = (group: ShepherdGroup) => { setEditing(group); setInput(group.report ? {smallGroupMeetingCount: String(group.report.smallGroupMeetingCount), holyWaveCount: String(group.report.holyWaveCount), otherWorshipCount: String(group.report.otherWorshipCount), note: group.report.note ?? ''} : {smallGroupMeetingCount: '0', holyWaveCount: '0', otherWorshipCount: '0', note: ''}); setError(null); };
  const save = async (status: 'DRAFT' | 'SUBMITTED') => { if (!editing || saving) return; const validated = validateAttendanceInput(input); if (!validated.ok) { setError(validated.message); return; } setSaving(true); try { await api.saveAdminReport(await getAccessToken(), campusId, editing.groupId, serviceDate, {...validated.value, status, version: editing.report?.version ?? 0}); setEditing(null); await load(); } catch { setError('저장하지 못했습니다. 최신 내용을 확인해 주세요.'); } finally { setSaving(false); } };
  const create = async () => { if (!newGroupName.trim() || newAssignees.length === 0 || saving) return; setSaving(true); try { await api.createGroup(await getAccessToken(), campusId, {name: newGroupName.trim(), assigneeUserIds: newAssignees}); setNewGroupName(''); setNewAssignees([]); await load(); } catch { setError('목장을 생성하지 못했습니다. 이름과 담당자를 확인해 주세요.'); } finally { setSaving(false); } };
  const openAssignees = (group: ShepherdGroup) => { setAssigneeGroup(group); setAssigneeSelection(group.assignees?.map((item) => item.userId) ?? []); setError(null); };
  const saveAssignees = async () => { if (!assigneeGroup || assigneeSelection.length === 0 || saving) return; setSaving(true); try { await api.updateAssignees(await getAccessToken(), campusId, assigneeGroup.groupId, assigneeSelection); setAssigneeGroup(null); await load(); } catch { setError('담당자를 변경하지 못했습니다. 최소 한 명을 선택해 주세요.'); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow="관리자" title="목홀타 관리" subtitle="목장별 제출 현황과 참여 인원을 확인합니다." action={<Pressable accessibilityLabel="목홀타 관리 닫기" onPress={onBack}><Text style={styles.link}>닫기</Text></Pressable>} />
    <View style={styles.weekRow}><Pressable accessibilityLabel="이전 주일" onPress={() => moveWeek(-7)} style={styles.weekButton}><Text>‹</Text></Pressable><Text style={styles.week}>{serviceDate} 주일</Text><Pressable accessibilityLabel="다음 주일" onPress={() => moveWeek(7)} style={styles.weekButton}><Text>›</Text></Pressable></View>
    {data ? <View accessibilityLabel="목홀타 전체 합계" style={styles.totals}><Total label="목장모임" value={data.totals.smallGroupMeetingCount}/><Total label="홀리웨이브" value={data.totals.holyWaveCount}/><Total label="타예배" value={data.totals.otherWorshipCount}/></View> : null}
    <View style={styles.filters}>{(['ALL','SUBMITTED','MISSING'] as const).map((value) => <Pressable accessibilityLabel={`${value === 'ALL' ? '전체' : value === 'SUBMITTED' ? '제출' : '미제출'} 목장 보기`} key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value ? styles.filterSelected : null]}><Text style={filter === value ? styles.filterSelectedText : null}>{value === 'ALL' ? '전체' : value === 'SUBMITTED' ? '제출' : '미제출'}</Text></Pressable>)}</View>
    {loading && !data ? <Loading message="목홀타 현황을 불러오고 있어요." /> : width >= 760 ? <AdminTable groups={rows} onEdit={startEdit} onManageAssignees={openAssignees} /> : <View style={styles.list}>{rows.map((group) => <AdminCard group={group} key={group.groupId} onEdit={startEdit} onManageAssignees={openAssignees} />)}</View>}
    {data && data.totalPages > 1 ? <View style={styles.pager}><Button accessibilityLabel="이전 목장 페이지" disabled={page === 0} onPress={() => setPage((value) => value - 1)} variant="secondary">이전</Button><Text>{page + 1}/{data.totalPages}</Text><Button accessibilityLabel="다음 목장 페이지" disabled={page + 1 >= data.totalPages} onPress={() => setPage((value) => value + 1)} variant="secondary">다음</Button></View> : null}
    {editing ? <View accessibilityLabel="목장 보고 편집" style={styles.editor}><Text style={styles.heading}>{editing.groupName} 입력</Text>{(['smallGroupMeetingCount','holyWaveCount','otherWorshipCount'] as const).map((key, index) => <TextInput accessibilityLabel={['목장모임 참여 인원','홀리웨이브 참여 인원','타예배 참여 인원'][index]} key={key} keyboardType="number-pad" onChangeText={(text) => setInput((current) => ({...current, [key]: text.replace(/[^0-9]/g, '')}))} placeholder={['목장모임','홀리웨이브','타예배'][index]} style={styles.input} value={input[key]} />)}<TextInput accessibilityLabel="목홀타 메모" multiline onChangeText={(note) => setInput((current) => ({...current, note}))} placeholder="메모 (선택)" style={styles.input} value={input.note}/><View style={styles.editorActions}><Button accessibilityLabel="목장 보고 편집 취소" onPress={() => setEditing(null)} variant="secondary">취소</Button><Button accessibilityLabel="관리자 목홀타 임시 저장" disabled={saving} onPress={() => void save('DRAFT')} variant="secondary">임시 저장</Button><Button accessibilityLabel="관리자 목홀타 제출 저장" disabled={saving} onPress={() => void save('SUBMITTED')}>제출 저장</Button></View></View> : null}
    {assigneeGroup ? <View accessibilityLabel="목장 담당자 관리" style={styles.editor}><Text style={styles.heading}>{assigneeGroup.groupName} 담당자</Text><Text style={styles.caption}>담당자는 한 명 이상 유지해야 합니다.</Text><MemberChoices members={members} selected={assigneeSelection} setSelected={setAssigneeSelection} prefix="기존 목장"/><View style={styles.editorActions}><Button accessibilityLabel="담당자 변경 취소" onPress={() => setAssigneeGroup(null)} variant="secondary">취소</Button><Button accessibilityLabel="담당자 변경 저장" disabled={saving || assigneeSelection.length === 0} onPress={() => void saveAssignees()}>담당자 저장</Button></View></View> : null}
    <View style={styles.editor}><Text style={styles.heading}>목장 생성</Text><TextInput accessibilityLabel="관리자 새 목장 이름" onChangeText={setNewGroupName} placeholder="목장 이름" style={styles.input} value={newGroupName}/><Text style={styles.caption}>담당자를 한 명 이상 선택해 주세요.</Text><View style={styles.members}>{members.map((member) => { const id = member.userId ?? member.id; if (!id) return null; const selected = newAssignees.includes(id); return <Pressable accessibilityLabel={`${member.name} 담당자 ${selected ? '해제' : '선택'}`} key={id} onPress={() => setNewAssignees((current) => selected ? current.filter((value) => value !== id) : [...current, id])} style={[styles.member, selected ? styles.memberSelected : null]}><Text style={selected ? styles.memberSelectedText : null}>{member.name}</Text></Pressable>; })}</View><Button accessibilityLabel="관리자 목장 생성" disabled={saving || !newGroupName.trim() || newAssignees.length === 0} onPress={() => void create()}>목장 생성</Button></View>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
  </ScrollView>;
}

function Total({label, value}: {label: string; value: number}) { return <View style={styles.total}><Text style={styles.caption}>{label}</Text><Text style={styles.totalValue}>{value}명</Text></View>; }
function AdminCard({group, onEdit, onManageAssignees}: {group: ShepherdGroup; onEdit: (group: ShepherdGroup) => void; onManageAssignees: (group: ShepherdGroup) => void}) { return <View accessibilityLabel={`${group.groupName} 목홀타 현황`} style={styles.card}><View style={styles.cardHeader}><Text style={styles.heading}>{group.groupName}</Text><Text style={group.report?.status === 'SUBMITTED' ? styles.submitted : styles.missing}>{group.report?.status === 'SUBMITTED' ? '제출' : '미제출'}</Text></View><Text style={styles.caption}>{group.assignees?.map((item) => item.name).join(', ') ?? '담당자 확인 필요'}</Text><Text style={styles.numbers}>목장모임 {group.report?.smallGroupMeetingCount ?? 0} · 홀리웨이브 {group.report?.holyWaveCount ?? 0} · 타예배 {group.report?.otherWorshipCount ?? 0}</Text>{group.report ? <Text style={styles.caption}>마지막 수정 {group.report.lastModifiedByName ?? '담당자'} · {formatModifiedAt(group.report.lastModifiedAt)}</Text> : null}<View style={styles.editorActions}><Button accessibilityLabel={`${group.groupName} 담당자 관리`} onPress={() => onManageAssignees(group)} variant="secondary">담당자</Button><Button accessibilityLabel={`${group.groupName} 목홀타 수정`} onPress={() => onEdit(group)} variant="secondary">수정</Button></View></View>; }
function AdminTable({groups, onEdit, onManageAssignees}: {groups: ShepherdGroup[]; onEdit: (group: ShepherdGroup) => void; onManageAssignees: (group: ShepherdGroup) => void}) { return <View style={styles.table}><View style={styles.tableRow}><Text style={styles.cell}>목장</Text><Text style={styles.cell}>담당자</Text><Text style={styles.cell}>목모</Text><Text style={styles.cell}>홀리</Text><Text style={styles.cell}>타예배</Text><Text style={styles.cell}>상태</Text><Text style={styles.cell}>마지막 수정</Text><Text style={styles.cell}>명령</Text></View>{groups.map((group) => <View key={group.groupId} style={styles.tableRow}><Text style={styles.cell}>{group.groupName}</Text><Pressable accessibilityLabel={`${group.groupName} 담당자 관리`} onPress={() => onManageAssignees(group)} style={styles.cell}><Text>{group.assignees?.map((item) => item.name).join(', ')}</Text></Pressable><Text style={styles.cell}>{group.report?.smallGroupMeetingCount ?? 0}</Text><Text style={styles.cell}>{group.report?.holyWaveCount ?? 0}</Text><Text style={styles.cell}>{group.report?.otherWorshipCount ?? 0}</Text><Text style={styles.cell}>{group.report?.status === 'SUBMITTED' ? '제출' : '미제출'}</Text><Text style={styles.cell}>{group.report ? `${group.report.lastModifiedByName ?? '담당자'} ${formatModifiedAt(group.report.lastModifiedAt)}` : '-'}</Text><Pressable accessibilityLabel={`${group.groupName} 수정`} onPress={() => onEdit(group)}><Text style={styles.link}>수정</Text></Pressable></View>)}</View>; }
function MemberChoices({members, prefix, selected, setSelected}: {members: Member[]; prefix: string; selected: number[]; setSelected: React.Dispatch<React.SetStateAction<number[]>>}) { return <View style={styles.members}>{members.map((member) => { const id = member.userId ?? member.id; if (!id) return null; const active = selected.includes(id); return <Pressable accessibilityLabel={`${prefix} ${member.name} 담당자 ${active ? '해제' : '선택'}`} key={id} onPress={() => setSelected((current) => active ? current.filter((value) => value !== id) : [...current, id])} style={[styles.member, active ? styles.memberSelected : null]}><Text style={active ? styles.memberSelectedText : null}>{member.name}</Text></Pressable>; })}</View>; }
function currentSunday() { const now = new Date(); const seoul = new Date(now.getTime() + 9 * 60 * 60 * 1000); seoul.setUTCDate(seoul.getUTCDate() - seoul.getUTCDay()); return seoul.toISOString().slice(0, 10); }
function formatDate(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function formatModifiedAt(value: string) { const date = new Date(value); return Number.isFinite(date.getTime()) ? date.toLocaleString('ko-KR', {month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit'}) : '-'; }
const styles = StyleSheet.create({screen: {backgroundColor: colors.background, gap: spacing.gap, padding: spacing.card, paddingBottom: 60}, link: {color: colors.primary, fontWeight: '800'}, weekRow: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'}, weekButton: {alignItems: 'center', backgroundColor: colors.neutralSoft, borderRadius: 18, height: 40, justifyContent: 'center', width: 40}, week: {color: colors.text, fontSize: 16, fontWeight: '800'}, totals: {flexDirection: 'row', gap: 8}, total: {backgroundColor: colors.primarySoft, borderRadius: radius.control, flex: 1, padding: 12}, totalValue: {color: colors.primary, fontSize: 19, fontWeight: '900', marginTop: 4}, filters: {flexDirection: 'row', gap: 8}, filter: {backgroundColor: colors.neutralSoft, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 8}, filterSelected: {backgroundColor: colors.primary}, filterSelectedText: {color: '#fff', fontWeight: '800'}, list: {gap: 10}, card: {backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1, gap: 8, padding: spacing.gap}, cardHeader: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'}, heading: {color: colors.text, fontSize: 17, fontWeight: '900'}, submitted: {color: colors.success, fontWeight: '800'}, missing: {color: colors.warning, fontWeight: '800'}, caption: {color: colors.mutedText, fontSize: 13}, numbers: {color: colors.text, fontSize: 14, lineHeight: 21}, pager: {alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'center'}, editor: {backgroundColor: colors.surface, borderRadius: radius.card, gap: 10, padding: spacing.gap}, input: {borderColor: colors.border, borderRadius: radius.control, borderWidth: 1, color: colors.text, minHeight: 46, paddingHorizontal: 12}, editorActions: {gap: 8}, members: {flexDirection: 'row', flexWrap: 'wrap', gap: 8}, member: {backgroundColor: colors.neutralSoft, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8}, memberSelected: {backgroundColor: colors.primary}, memberSelectedText: {color: '#fff'}, error: {color: colors.danger}, table: {backgroundColor: colors.surface, borderRadius: radius.control, overflow: 'hidden'}, tableRow: {alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', minHeight: 46, paddingHorizontal: 8}, cell: {color: colors.text, flex: 1, fontSize: 12}});
