import fs from 'node:fs';
import {createRequire} from 'node:module';
import path from 'node:path';

import {describe, expect, it} from 'vitest';

const root = path.resolve(import.meta.dirname, '../..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');
const appJson = JSON.parse(read('app.json'));
const packageJson = JSON.parse(read('package.json'));
const appConfig = read('app.config.js');
const releasePlugin = read('plugins/withAndroidReleaseRecommendations.js');
const require = createRequire(import.meta.url);
const {__internal} = require('../../plugins/withAndroidReleaseRecommendations.js');

describe('Android production release recommendations', () => {
  it('publishes the next user-facing app version consistently', () => {
    expect(appJson.expo.version).toBe('1.1.2');
    expect(packageJson.version).toBe('1.1.2');
  });

  it('allows Android rotation and resizing without changing the iOS preference', () => {
    expect(appJson.expo.orientation).toBe('portrait');
    expect(appConfig).toContain("'./plugins/withAndroidReleaseRecommendations'");
    expect(releasePlugin).toContain("activity['android:resizeableActivity'] = 'true'");
    expect(releasePlugin).toContain("delete activity['android:screenOrientation']");
  });

  it('enables R8 code optimization and optimized resource shrinking', () => {
    expect(appConfig).toContain('enableMinifyInReleaseBuilds: true');
    expect(appConfig).toContain('enableShrinkResourcesInReleaseBuilds: true');

    const buildGradle = __internal.enableR8OptimizingDefaults(`
      release {
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
      }
    `);
    expect(buildGradle).toContain(
      'getDefaultProguardFile("proguard-android-optimize.txt")',
    );
    expect(buildGradle).not.toContain('getDefaultProguardFile("proguard-android.txt")');

    expect(
      __internal.enableOptimizedResourceShrinking([
        {type: 'property', key: 'android.useAndroidX', value: 'true'},
      ]),
    ).toContainEqual({
      type: 'property',
      key: 'android.r8.optimizedResourceShrinking',
      value: 'true',
    });
  });

  it('removes deprecated system-bar theme attributes generated by Expo', () => {
    expect(releasePlugin).toContain("'android:statusBarColor'");
    expect(releasePlugin).toContain("'android:navigationBarColor'");
    expect(releasePlugin).toContain("'android:navigationBarDividerColor'");
    expect(releasePlugin).toContain("'android:enforceStatusBarContrast'");
    expect(releasePlugin).toContain("'android:enforceNavigationBarContrast'");
  });
});
