import {useCallback, useEffect, useRef, useState} from 'react';
import {Pressable, StyleSheet, Switch, Text, TextInput, View} from 'react-native';

import {FaithLogApiError} from '../api/client';
import type {ApiError} from '../api/types';
import {resolveCurrentAccessToken} from '../auth/accessTokenResolver';
import {Button, Card, Empty, ErrorState, Loading, ScreenHeader, TextField} from '../components/ui';
import {colors, radius, spacing, typography} from '../theme';
import {announcementApi, type AnnouncementApi} from './announcementApi';
import {isAnnouncementMockModeEnabled} from './announcementEnvironment';
import {AnnouncementCategoryBadge} from './AnnouncementCategoryBadge';
import {moveUploadItem, type UploadItem} from './announcementMedia';
import type {AnnouncementCategory, AnnouncementDetail, AnnouncementSaveRequest, AnnouncementStatus, AnnouncementSummary} from './announcementTypes';

type Route = {name: 'list'} | {name: 'editor'; detail: AnnouncementDetail | null} | {name: 'categories'};
type LoadState = {status: 'loading'} | {status: 'success'; items: AnnouncementSummary[]} | {status: 'error'; error: ApiError};
const tabs: Array<{id: AnnouncementStatus; label: string}> = [{id: 'SCHEDULED', label: '게시 예정'}, {id: 'PUBLISHED', label: '게시됨'}, {id: 'ARCHIVED', label: '보관됨'}];
const isMockModeEnabled = isAnnouncementMockModeEnabled;

export function AdminAnnouncementScreen({campusId, api = announcementApi, onBack}: {api?: AnnouncementApi; campusId: number; onBack: () => void}) {
  const [route, setRoute] = useState<Route>({name: 'list'});
  const [status, setStatus] = useState<AnnouncementStatus>('PUBLISHED');
  const [state, setState] = useState<LoadState>({status: 'loading'});
  const requestRef = useRef(0);
  const withToken = useCallback(async <T,>(operation: (token: string) => Promise<T>) => { const token = await resolveCurrentAccessToken(() => undefined); if (!token) throw new FaithLogApiError({kind: 'sessionExpired', message: '로그인이 만료되었습니다.'}); return operation(token); }, []);
  const load = useCallback(async () => { const request = ++requestRef.current; setState({status: 'loading'}); try { const items = await withToken((token) => api.listAdmin(token, campusId, status)); if (request === requestRef.current) setState({status: 'success', items}); } catch (error) { if (request === requestRef.current) setState({status: 'error', error: toApiError(error)}); } }, [api, campusId, status, withToken]);
  useEffect(() => { void load(); }, [load]);
  const archive = useCallback(async (item: AnnouncementSummary) => {
    try {
      const token = await resolveCurrentAccessToken(() => undefined);
      if (!token) throw new Error('session');
      await api.archiveAnnouncement(token, campusId, item.id);
      await load();
    } catch {
      setState({status: 'error', error: {kind: 'error', message: '공지를 보관하지 못했습니다.'}});
    }
  }, [api, campusId, load, withToken]);

  if (route.name === 'editor') return <AnnouncementEditorScreen api={api} campusId={campusId} detail={route.detail} onBack={() => { setRoute({name: 'list'}); void load(); }} />;
  if (route.name === 'categories') return <AnnouncementCategoryScreen api={api} campusId={campusId} onBack={() => setRoute({name: 'list'})} />;
  return <AdminAnnouncementListScreen loadState={state} onArchive={archive} onBack={onBack} onCategories={() => setRoute({name: 'categories'})} onCreate={() => setRoute({name: 'editor', detail: null})} onEdit={(detail) => setRoute({name: 'editor', detail})} onRetry={load} onStatus={setStatus} selectedStatus={status} />;
}

export function AdminAnnouncementListScreen({loadState, onArchive, onBack, onCategories, onCreate, onEdit, onRetry, onStatus, selectedStatus}: {loadState: LoadState; onArchive: (item: AnnouncementSummary) => void; onBack: () => void; onCategories: () => void; onCreate: () => void; onEdit: (detail: AnnouncementDetail) => void; onRetry: () => void; onStatus: (status: AnnouncementStatus) => void; selectedStatus: AnnouncementStatus}) {
  return <View style={styles.page}><ScreenHeader eyebrow="캠퍼스 운영" title="공지 관리" subtitle="공지 작성, 예약 게시와 보관 상태를 관리합니다." action={<CompactButton label="뒤로" onPress={onBack} />} /><View style={styles.actionRow}><CompactButton label="카테고리" onPress={onCategories} /><CompactButton label="공지 작성" onPress={onCreate} primary /></View><View accessibilityRole="tablist" style={styles.tabs}>{tabs.map((tab) => <Pressable accessibilityRole="tab" accessibilityState={{selected: selectedStatus === tab.id}} key={tab.id} onPress={() => onStatus(tab.id)} style={[styles.tab, selectedStatus === tab.id && styles.tabActive]}><Text style={[styles.tabText, selectedStatus === tab.id && styles.tabTextActive]}>{tab.label}</Text></Pressable>)}</View>{loadState.status === 'loading' ? <Loading message="공지 목록을 불러오고 있습니다." /> : loadState.status === 'error' ? <ErrorState title="공지 목록을 불러오지 못했습니다" message="잠시 후 다시 시도해 주세요." actionLabel="다시 시도" actionAccessibilityLabel="관리자 공지 목록 다시 불러오기" onActionPress={onRetry} /> : loadState.items.length === 0 ? <Empty title="해당 상태의 공지가 없습니다" message="공지 작성에서 새 소식을 등록할 수 있습니다." actionLabel="공지 작성" actionAccessibilityLabel="새 공지 작성" onActionPress={onCreate} /> : loadState.items.map((item) => <View key={item.id} style={styles.card}><View style={styles.cardTop}><AnnouncementCategoryBadge category={item.category} /><Text style={styles.meta}>{item.pinned ? '상단 고정' : statusLabel(item.status)}</Text></View><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>{formatDate(item.publishAt)}</Text><View style={styles.actionRow}><CompactButton label="수정" onPress={() => onEdit(item)} />{item.status !== 'ARCHIVED' ? <CompactButton label="보관" onPress={() => onArchive(item)} /> : null}</View></View>)}</View>;
}

export function AnnouncementEditorScreen({api, campusId, detail, onBack}: {api: AnnouncementApi; campusId: number; detail: AnnouncementDetail | null; onBack: () => void}) {
  const [categories, setCategories] = useState<AnnouncementCategory[]>([]);
  const [categoryId, setCategoryId] = useState(detail?.category.id ?? 0);
  const [title, setTitle] = useState(detail?.title ?? '');
  const [body, setBody] = useState(detail?.body ?? '');
  const [pinned, setPinned] = useState(detail?.pinned ?? false);
  const [publishMode, setPublishMode] = useState<'NOW' | 'SCHEDULED'>(detail?.status === 'SCHEDULED' ? 'SCHEDULED' : 'NOW');
  const [publishAt, setPublishAt] = useState(detail?.publishAt ?? '');
  const [uploads, setUploads] = useState<UploadItem[]>(() => (detail?.imageAssetIds ?? []).map((assetId) => ({assetId, localId: `asset-${assetId}`, status: 'ready'})));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; void resolveCurrentAccessToken(() => undefined).then((token) => token ? api.listCategories(token, campusId, false) : []).then((items) => { if (!mounted.current) return; setCategories(items); setCategoryId((current) => current || items[0]?.id || 0); }).catch(() => mounted.current && setError('카테고리를 불러오지 못했습니다.')); return () => { mounted.current = false; }; }, [api, campusId]);
  const save = async () => { if (saving) return; const trimmedTitle = title.trim(); const trimmedBody = body.trim(); if (!trimmedTitle || !trimmedBody || !categoryId) { setError('카테고리, 제목과 본문을 입력해 주세요.'); return; } if (publishMode === 'SCHEDULED' && Number.isNaN(Date.parse(publishAt))) { setError('예약 게시 시각을 확인해 주세요.'); return; } setSaving(true); setError(null); try { const token = await resolveCurrentAccessToken(() => undefined); if (!token) throw new Error('session'); const request: AnnouncementSaveRequest = {body: trimmedBody, categoryId, imageAssetIds: uploads.filter((item): item is Extract<UploadItem, {status: 'ready'}> => item.status === 'ready').map((item) => item.assetId), pinned, publishAt: publishMode === 'SCHEDULED' ? publishAt : null, publishMode, title: trimmedTitle}; if (detail) await api.updateAnnouncement(token, campusId, detail.id, request); else await api.createAnnouncement(token, campusId, request); if (mounted.current) onBack(); } catch { if (mounted.current) setError('공지를 저장하지 못했습니다. 입력 내용은 그대로 보존됩니다.'); } finally { if (mounted.current) setSaving(false); } };
  return <View style={styles.page}><ScreenHeader eyebrow={detail ? '공지 수정' : '새 공지'} title={detail ? '공지 내용 수정' : '공지 작성'} action={<CompactButton label="뒤로" onPress={onBack} />} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Card><Text style={styles.label}>카테고리</Text><View style={styles.wrap}>{categories.map((category) => <Pressable accessibilityRole="radio" accessibilityState={{checked: categoryId === category.id}} key={category.id} onPress={() => setCategoryId(category.id)} style={[styles.choice, categoryId === category.id && styles.choiceActive]}><AnnouncementCategoryBadge category={category} /></Pressable>)}</View><TextField label="제목" onChangeText={setTitle} value={title} /><Text style={styles.label}>본문</Text><TextInput accessibilityLabel="공지 본문" multiline onChangeText={setBody} placeholder="공지 내용을 입력하세요" style={styles.multiline} textAlignVertical="top" value={body} /><View style={styles.switchRow}><Text style={styles.label}>상단 고정</Text><Switch accessibilityLabel="공지 상단 고정" onValueChange={setPinned} value={pinned} /></View><Text style={styles.label}>게시 방식</Text><View style={styles.tabs}><Choice label="지금 게시" selected={publishMode === 'NOW'} onPress={() => setPublishMode('NOW')} /><Choice label="예약 게시" selected={publishMode === 'SCHEDULED'} onPress={() => setPublishMode('SCHEDULED')} /></View>{publishMode === 'SCHEDULED' ? <TextField helper="예: 2026-08-05T09:00:00+09:00" label="예약 게시 시각" onChangeText={setPublishAt} value={publishAt} /> : null}</Card><AnnouncementImagePickerSection items={uploads} onChange={setUploads} /><Card><Text style={styles.label}>미리보기</Text>{categories.find((category) => category.id === categoryId) ? <AnnouncementCategoryBadge category={categories.find((category) => category.id === categoryId)!} /> : null}<Text style={styles.cardTitle}>{title.trim() || '공지 제목'}</Text><Text style={styles.previewBody}>{body.trim() || '공지 본문이 여기에 표시됩니다.'}</Text></Card><Button accessibilityLabel="공지 저장" disabled={saving} onPress={() => void save()}>{saving ? '저장 중' : '저장'}</Button></View>;
}

export function AnnouncementCategoryScreen({api, campusId, onBack}: {api: AnnouncementApi; campusId: number; onBack: () => void}) {
  const [items, setItems] = useState<AnnouncementCategory[]>([]); const [name, setName] = useState(''); const [color, setColor] = useState('#3182F6'); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { const token = await resolveCurrentAccessToken(() => undefined); if (!token) return; setItems(await api.listCategories(token, campusId, true)); } catch { setError('카테고리를 불러오지 못했습니다.'); } }, [api, campusId]);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (saving || !name.trim()) return; setSaving(true); setError(null); try { const token = await resolveCurrentAccessToken(() => undefined); if (!token) throw new Error('session'); await api.createCategory(token, campusId, {color, isActive: true, name: name.trim(), sortOrder: items.length}); setName(''); await load(); } catch { setError('같은 이름이 있는지 확인하고 다시 시도해 주세요.'); } finally { setSaving(false); } };
  const toggle = async (item: AnnouncementCategory) => { try { const token = await resolveCurrentAccessToken(() => undefined); if (!token) return; await api.updateCategory(token, campusId, item.id, {...item, isActive: !item.isActive}); await load(); } catch { setError('카테고리 상태를 변경하지 못했습니다.'); } };
  return <View style={styles.page}><ScreenHeader eyebrow="공지 관리" title="카테고리 관리" subtitle="사용 중인 카테고리는 삭제 대신 비활성화합니다." action={<CompactButton label="뒤로" onPress={onBack} />} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Card><TextField label="카테고리 이름" onChangeText={setName} value={name} /><Text style={styles.label}>색상</Text><View style={styles.wrap}>{['#3182F6', '#5BA8B0', '#F59E0B', '#EF4444', '#22C55E'].map((swatch) => <Pressable accessibilityLabel={`카테고리 색상 ${swatch}`} accessibilityRole="radio" accessibilityState={{checked: color === swatch}} key={swatch} onPress={() => setColor(swatch)} style={[styles.swatch, {backgroundColor: swatch}, color === swatch && styles.swatchSelected]} />)}</View><Button accessibilityLabel="카테고리 추가" disabled={saving || !name.trim()} onPress={() => void create()}>추가</Button></Card>{items.map((item) => <View key={item.id} style={styles.categoryRow}><AnnouncementCategoryBadge category={item} /><Text style={styles.meta}>{item.isActive ? '활성' : '비활성'}</Text><CompactButton label={item.isActive ? '비활성화' : '활성화'} onPress={() => void toggle(item)} /></View>)}</View>;
}

function AnnouncementImagePickerSection({items, onChange}: {items: UploadItem[]; onChange: (items: UploadItem[]) => void}) { const mock = isMockModeEnabled(); const add = () => { const assetId = 9000 + items.length; onChange([...items, {assetId, localId: `mock-${assetId}`, status: 'ready'}]); }; return <Card><View style={styles.cardTop}><Text style={styles.label}>이미지</Text>{mock ? <CompactButton label="샘플 추가" onPress={add} /> : null}</View><Text style={styles.meta}>{mock ? 'Mock에서는 여러 이미지의 추가, 삭제와 순서를 확인할 수 있습니다.' : '이미지 선택은 네이티브 업로드 계약 확정 후 제공됩니다.'}</Text>{items.map((item, index) => <View key={item.localId} style={styles.uploadRow}><Text style={styles.meta}>이미지 {index + 1} · {item.status === 'ready' ? '업로드 완료' : item.status === 'uploading' ? `${Math.round(item.progress * 100)}%` : '재시도 필요'}</Text><View style={styles.actionRow}><CompactButton label="위" onPress={() => onChange(moveUploadItem(items, index, Math.max(0, index - 1)))} /><CompactButton label="아래" onPress={() => onChange(moveUploadItem(items, index, Math.min(items.length - 1, index + 1)))} /><CompactButton label="삭제" onPress={() => onChange(items.filter((candidate) => candidate.localId !== item.localId))} /></View></View>)}</Card>; }
function Choice({label, onPress, selected}: {label: string; onPress: () => void; selected: boolean}) { return <Pressable accessibilityRole="radio" accessibilityState={{checked: selected}} onPress={onPress} style={[styles.tab, selected && styles.tabActive]}><Text style={[styles.tabText, selected && styles.tabTextActive]}>{label}</Text></Pressable>; }
function CompactButton({label, onPress, primary = false}: {label: string; onPress: () => void; primary?: boolean}) { return <Pressable accessibilityLabel={label} accessibilityRole="button" hitSlop={6} onPress={onPress} style={({pressed}) => [styles.compact, primary && styles.compactPrimary, pressed && styles.pressed]}><Text style={[styles.compactText, primary && styles.compactPrimaryText]}>{label}</Text></Pressable>; }
function statusLabel(status: AnnouncementStatus) { return status === 'PUBLISHED' ? '게시됨' : status === 'SCHEDULED' ? '게시 예정' : '보관됨'; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('ko-KR', {dateStyle: 'medium', timeStyle: 'short'}).format(new Date(value)) : '게시 시각 미정'; }
function toApiError(error: unknown): ApiError { return error instanceof FaithLogApiError ? error.detail : {kind: 'error', message: '요청을 처리하지 못했습니다.'}; }

const styles = StyleSheet.create({actionRow: {alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'flex-end'}, card: {backgroundColor: colors.surface, borderRadius: radius.card, gap: 10, padding: spacing.card}, cardTitle: {...typography.cardTitle, color: colors.textPrimary}, cardTop: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'}, categoryRow: {alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.item, flexDirection: 'row', gap: 10, padding: 14}, choice: {borderColor: colors.borderSoft, borderRadius: radius.control, borderWidth: 1, padding: 4}, choiceActive: {borderColor: colors.primary}, compact: {alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: radius.pill, justifyContent: 'center', minHeight: 44, paddingHorizontal: 12}, compactPrimary: {backgroundColor: colors.primary}, compactPrimaryText: {color: colors.surface}, compactText: {color: colors.primary, fontSize: 13, fontWeight: '800'}, error: {color: colors.danger, fontSize: 14, lineHeight: 20}, label: {...typography.label, color: colors.textPrimary}, meta: {color: colors.textMuted, flex: 1, fontSize: 13, lineHeight: 18}, multiline: {backgroundColor: colors.background, borderColor: colors.borderSoft, borderRadius: radius.control, borderWidth: 1, color: colors.textPrimary, fontSize: 15, minHeight: 144, padding: 14}, page: {gap: spacing.gap, paddingBottom: 120}, pressed: {opacity: 0.7}, previewBody: {...typography.body, color: colors.textSecondary}, swatch: {borderRadius: 18, height: 36, width: 36}, swatchSelected: {borderColor: colors.textPrimary, borderWidth: 3}, switchRow: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'}, tab: {alignItems: 'center', borderRadius: radius.control, flex: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 8}, tabActive: {backgroundColor: colors.surface}, tabText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'}, tabTextActive: {color: colors.primary}, tabs: {backgroundColor: colors.borderSoft, borderRadius: radius.control, flexDirection: 'row', gap: 4, padding: 4}, uploadRow: {backgroundColor: colors.background, borderRadius: radius.item, gap: 8, padding: 12}, wrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 8}});
